class ValidationHelpers

  $tot_participants_db = CouchRest.database("http://localhost:5984/tot_participants_2016_12")
  $cso_gcode_db = CouchRest.database("http://localhost:5984/cso_gcodes_2016_12")
  $tusome_teacher_code_db = CouchRest.database("http://localhost:5984/tusometeacher_codes_2017_1")
  $tusome_apbet_code_db = CouchRest.database("http://localhost:5984/tusomeapbet_codes_2017_1")

  def self.closest_animal(animal)
    FuzzyMatch.new(JSON.parse(IO.read("animals.json"))).find(animal)
  end

  def self.closest_city(city)
    FuzzyMatch.new(JSON.parse(IO.read("countriesToCities.json")).values.flatten).find(city)
  end
    
  def self.valid_counties
    [
      "BARINGO",
      "BOMET",
      "BUNGOMA",
      "BUSIA",
      "ELGEYO-MARAKWET",
      "EMBU",
      "GARISSA",
      "HOMA BAY",
      "ISIOLO",
      "KAJIADO",
      "KAKAMEGA",
      "KERICHO",
      "KIAMBU",
      "KILIFI",
      "KIRINYAGA",
      "KISII",
      "KISUMU",
      "KITUI",
      "KWALE",
      "LAIKIPIA",
      "LAMU",
      "MACHAKOS",
      "MAKUENI",
      "MANDERA",
      "MARSABIT",
      "MERU",
      "MIGORI",
      "MOMBASA",
      "MURANG'A",
      "NAIROBI CITY",
      "NAKURU",
      "NANDI",
      "NAROK",
      "NYAMIRA",
      "NYANDARUA",
      "NYERI",
      "SAMBURU",
      "SIAYA",
      "TAITA-TAVETA",
      "TANA RIVER",
      "THARAKA-NITHI",
      "TRANS NZOIA",
      "TURKANA",
      "UASIN GISHU",
      "VIHIGA",
      "WAJIR",
      "WEST POKOT"
    ]
  end

  def self.closest_valid_county_match(county_name)
    return county_name.upcase if self.valid_counties.include? county_name.upcase
    return FuzzyMatch.new(self.valid_counties).find(county_name.upcase)
  end

  # Poorly named, but leaving for legacy purposes
  def self.closest_match(county_name)
    self.closest_valid_county_match(county_name)
  end

  def self.error_from_invalid_kenya_county(county_name)
    return nil if self.valid_counties.include? county_name.upcase
    closest_match = FuzzyMatch.new(valid_counties).find(county_name.upcase)
    return "#{county_name} is not a valid county. Do you mean #{closest_match}?"
  end

  def self.tot_participant_info(tot_code)
    $tot_participants_db.get(tot_code)
  end

  def self.tot_participant_info_string(tot_code)
    begin
      result = $tot_participants_db.get(tot_code)
    rescue
      return "No Match"
    end
    "#{result['TOT Code']}: #{result['Name']}, #{result['Organization']}, #{result['Designation']}, #{result['County']}, #{result['Job Group']}"
  end

  def self.cso_gcode_lookup(gcode)
    $cso_gcode_db.get(gcode)
  end

  def self.cso_gcode_string(gcode)
    begin
      result = $cso_gcode_db.get(gcode)
    rescue
      return "No Match: #{gcode}" unless result
    end
    "[#{result['_id']}] County: #{result['County']}, Zone: #{result['Zone']}, Training Centre: #{result['Training Centre Code']}"
  end


  def self.tusometeacher_code_string(tusome_code)
    begin
      result = $tusome_teacher_code_db.get(tusome_code)
    rescue
      return "No Match: #{tusome_code}" unless result
    end
    if result.nil?
      return "No Match: #{tusome_code}" unless result
    end
    "[#{result['_id']}] County: #{result['County']}, Zone: #{result['Zone']}, School Name: #{result['School Name']}"
  end

  def self.tusomeapbet_code_string(tusome_code)
    begin
      result = $tusome_apbet_code_db.get(tusome_code)
    rescue
      return "No Match: #{tusome_code}" unless result
    end
    if result.nil?
      return "No Match: #{tusome_code}" unless result
    end
    "[#{result['_id']}] County: #{result['County']}, Cluster: #{result['Cluster']}, School Name: #{result['School Name']}"
  end

  def self.add_data(message, view)
    begin
      result = $db.view("#{view}/#{view}", {
        "key" => message.from(),
        "include_docs" => false,
        "limit" => 1
      })['rows'][0]
    rescue Exception => e
      puts e.to_yaml
      return "No Match" unless result
    end
    if result.nil?
      puts "No match"
      return "No Match" unless result
    end
    message.add_and_save_results(result["value"].map{ |property,value|
      {
        "question_name" => property,
        "answer" => value,
        "valid" => true
      }
    })
  end

  def self.valid_schools
    [
      "A E F Reuben Primary",
      "Bondeni Primary",
      "Busara Primary",
      "Doonholm Primary",
      "Edelvale Primary",
      "Embakasi Garrison Primary",
      "Embakasi Primary",
      "Imara Primary",
      "Kayole I Primary",
      "Kifaru Primary",
      "Komarock Primary",
      "Kwa Njenga Primary",
      "Mwangaza Primary",
      "Our Lady Of Nazareth Primary",
      "Peter Kibukosya Primary",
      "Thawabu Primary",
      "Tumaini Primary",
      "Umoja I Primary",
      "Unity Primary",
      "Utawala Academy",
      "Mugumo Day Nursery",
      "Mwangaza Day Nursery",
      "Simba Day Nursery",
      "Umoja 1 Day Nursery",
      "Unity Day Nursery",
      "Eastleigh Primary",
      "Moi Air Base Primary",
      "Moi Forces Academy",
      "New Eastleigh Primary",
      "New Pumwani Primary",
      "St Teresas Boys Primary",
      "Zawadi Primary",
      "Njoro Day Nursery ",
      "Pumwani Nursery",
      "Shauri Moyo Day Nursery",
      "Starehe Day Nursery",
      "Tana Day Nursery ",
      "Ziwani Day Nursery",
      "Bahati Primary Ecd",
      "Buruburu 1",
      "Dr.Livingstone Primary",
      "Heshima Road Primary",
      "Kimathi Estate Primary",
      "Morrison Primary School Ecde",
      "Muthurwa  Ecde Centre",
      "Nairobi River Primary",
      "Our Lady Of Mercy Primary Ecd",
      "Uhuru Estate Primary Ecde",
      "C G H U Primary",
      "City Primary",
      "Dr Aggrey Primary",
      "Islamia Primary",
      "Moi Avenue Primary",
      "Muranga Road Primary",
      "Parklands Primary",
      "Pumwani Primary",
      "Riverbank Primary",
      "St Brigids Primary",
      "St Peter Clavers Primary",
      "Juja Road Primary",
      "Racecourse Primary",
      "Ainsworth Primary",
      "Muslim Primary",
      "Pangani Primary",
      "Park Road Primary",
      "Valley Bridge Primary School",
      "Daima Ecd",
      "Huruma Ecd Centre",
      "St Teresas Girls Pre Primary Section",
      "Salama Primary",
      "Ndururuno Ecd Centre",
      "Mathari Ecd",
      "Kiboro Ecd Centre",
      "Central Day Nursery",
      "Ngara East Day Nursery",
      "Jacaranda Special",
      "Kabete Vet Lab Primary",
      "Kangemi Primary",
      "Kihumbuini Primary",
      "Kileleshwa Primary",
      "Kilimani Primary",
      "Milimani Primary",
      "Muthangari Primary",
      "Nairobi Primary",
      "New Kihumbuini Primary",
      "St Georges Primary",
      "State House Primary",
      "Lavington Primary",
      "Kileleshwa Day Nursery ",
      "Lady Northey Day Nursery",
      "State House Day Nursery",
      "Hospital Hill Primary",
      "Aga Khan Primary",
      "Highridge Primary",
      "North Highridge Primary",
      "Visa Oshwal Primary",
      "Westlands Primary",
      "Bohra Road Primary",
      "Karura Forest Primary",
      "Loresho Primary",
      "Lower Kabete Primary",
      "Farasi Lane Primary",
      "Cheleta Primary",
      "Muguga Green Primary",
      "Parklands Day Nursery",
      "Joseph Apudo Primary",
      "Kaloleni Primary",
      "Makongeni Primary",
      "Mariakani Primary",
      "Mukuru Kayaba Primary",
      "Nairobi South Primary",
      "Our Lady Of Mercy Nairobi South Primary",
      "Plainsview Primary",
      "St Johns Primary",
      "St Catherines Primary",
      "St Bakhita Primary",
      "St Elizabeth Primary",
      "Star Of Hope Primary Lunga Lunga",
      "St Michaels Ecde Center",
      "St Pauls Primary",
      "St Annes Primary",
      "Rabai Road Primary",
      "Dr Krapf Primary",
      "St Patricks Primary",
      "Canon Apolo Primary",
      "Bidii Primary School",
      "Baraka Primary School",
      "Martin Luther Primary",
      "Jogoo Road Primary",
      "Harambee Primary School",
      "Ofafa Jericho Primary School",
      "Bahati Day Nursery ",
      "Mbotela Day Nursery",
      "Ofafa Maringo",
      "Kaloleni Day Nursery",
      "Thika Road Primary",
      "Drive Inn Primary School",
      "Muthaiga Primary",
      "Mm Chandaria Primary",
      "Baba Dogo Primary",
      "Daniel Komboni Primary",
      "Kariobangi North Primary",
      "Mathare North Primary",
      "Ngunyumu Primary",
      "Heidemarie Mathare 4 A Primary",
      "Marura Primary School",
      "Njathaini Primary School",
      "Kiwanja Primary School",
      "Mahiga Primary School",
      "Marurui Primary School",
      "Kahawa Primary School",
      "Kamiti Primary School",
      "Kahawa Garisson Preparatory",
      "Kenyatta University Primary",
      "Murema Ecd Centre",
      "Kasarani Primary",
      "Roysambu Primary",
      "Garden Estate Primary",
      "Githurai Primary",
      "Joseph Kangethe Primary",
      "Nembu Primary",
      "Ruthimitu Primary",
      "Kagira Primary",
      "Dr Muthiora Primary",
      "Mukarara Primary",
      "Mutuini Primary School",
      "Kirigu Primary",
      "Ndurarua Primary",
      "Kitiba Primary",
      "Dagoretti Primary Ecde Centre",
      "Gatina Ecde",
      "Jamhuri Primary School Ecde",
      "Joseph Kangethe  Ecde Centre",
      "Kabiria Primary",
      "Kawangware Primary Ecde Centre",
      "Kinyanjui Road Primary",
      "Mbagathi Road",
      "Riruta Hgm Primary",
      "Riruta Satelite Primary",
      "Shadrack Kimalel Ecde Centre",
      "Toi Primary Ecde Centre",
      "Madaraka Primary",
      "Kongoni Primary",
      "Langata Road Primary",
      "Ngei Primary",
      "Langata West Primary",
      "Uhuru Gardens Primary",
      "Nairobi West Day Nursery",
      "Ayany",
      "Karen C Primary School",
      "Kibera Primary Ecde",
      "Ngong Forest Primary",
      "Raila Education Center",
      "St. Mary'S Primary School",
      "Athi Primary Ecde ",
      "Dandora",
      "Dandora Day Nursery",
      "Drumvale",
      "Gituamba",
      "James Gichuru",
      "Jehova Jireh",
      "Molem Super Loaf",
      "Kariobangi",
      "Kayole North Primary",
      "Maua",
      "Mihango Primary School",
      "Ng'Undu",
      " Njiru Primary School",
      "Ronald Ngala",
      "Ruai Primary",
      "St Dominic",
      "Tom Mboya",
      "Ushirika",
      "Wangu",
      "Bokish",
      "Bondeni",
      "Chumvi",
      "Doldol",
      "Enakishomi",
      "Ethi",
      "Feroz",
      "Ildorot",
      "Ilmoran",
      "Jikaze",
      "Kairigire",
      "Kairigire Bidii",
      "Kantana",
      "Katunga",
      "Kiwanja Ndege",
      "Kurikuri",
      "Lariokoror",
      "Loilagai",
      "Lokusero",
      "Makamiamo",
      "Mia Moja",
      "Nandungoro",
      "Nanyoki",
      "Ngare Ndare",
      "Ngenia",
      "Ol Arjijo",
      "Ol Tasha",
      "Olkinyei",
      "Olkirisiai",
      "Ositat",
      "Sanga",
      "Sieku",
      "Sirimon",
      "Naimalal",
      "Emilango",
      "Lorian",
      "Lusugut",
      "Oloruko",
      "Olotiki",
      "Sosian",
      "Ol Maisor",
      "Island",
      "Marula Narok",
      "Mathanji",
      "Narok",
      "Kandutura",
      "Bombo",
      "Ndonyoriwo",
      "Lonyek",
      "Minjore",
      "Merigwiti",
      "Ndunyu",
      "Gathanji",
      "Magadi",
      "Miharati",
      "Ngoisusu",
      "Survey",
      "Nakwang",
      "Olmoran",
      "Githima",
      "Kahuho",
      "Mithuri",
      "Mwireri",
      "Mirango",
      "Niloriti",
      "Ngare Mare",
      "Dam Mbili",
      "Maundu Meri",
      "Ol-Motunyi",
      "Mutarakwa",
      "Majimbogo",
      "Lorora",
      "Kaptagat",
      "Sirat",
      "Shilor Naibor",
      "Ol Jogi",
      "Ol Jogi Pyrmid",
      "Tumaini",
      "Ccm Naibor",
      "Uaso Nyiro",
      "Ngare Ngiro",
      "Nazerene",
      "Lekisargei",
      "Pois",
      "Tangi Nyeusi",
      "Ol Girigiri",
      "Endana",
      "Mutirithia",
      "Muramati",
      "Lairagwan",
      "Mukima",
      "Ereri",
      "Mbogo Ini",
      "Soit Puus",
      "Reteti",
      "Facebook",
      "Lekiji",
      "Namnyak",
      "Dupata",
      "Emurua ecde",
      "Ewaso",
      "Ilmotiok ecde",
      "Ilpolei",
      "Ilpolei centre",
      "Kiganjo",
      "Kijabe ecde centre",
      "Kimanjo ecde centre",
      "Kurum ecde centre",
      "Leruk ecde Centre",
      "Loiborsoit",
      "Loosinya",
      "Lorubae ecde centre",
      "Loshaki ecde centre",
      "Narupa",
      "Munishoi",
      "Murpusi",
      "Naiperere",
      "Naserian Ecde centre",
      "Ndonyo Napi ecde centre",
      "Ngabolo",
      "Njurum",
      "Nkiroriti ecde",
      "Nosirai",
      "Nooltoijo",
      "Munipisha ecde",
      "Rongai",
      "Saramba",
      "Soit Oitashe",
      "Soit oudo",
      "Tiamamut",
      "Tool",
      "Tura",
      "Wakumbe",
      "Musul",
      "Loshaki ecde centre",
      "Bustani",
      "Eighteen",
      "G G Kinamba",
      "Kahuho",
      "Karia Ini",
      "Kariko",
      "Kisima",
      "Kiwanja",
      "Lobere",
      "Mahua",
      "Makutano",
      "Mbogoini",
      "Milimani",
      "Mithiga",
      "Muteta",
      "Mwenje",
      "Naigera",
      "Ndindika",
      "Ngelesha",
      "Njorua",
      "Nyakiambi",
      "Nyakinyua",
      "Olarabel",
      "St Kizito",
      "Tandare",
      "Warero",
      "Chereta",
      "Gatami",
      "Gatirima",
      "Gatitu",
      "Gituamba",
      "Kabage",
      "Kangumo",
      "Kanyuka",
      "Karaba",
      "Karandi Township",
      "Kiambogo",
      "Kinguka",
      "Kiriti",
      "Kite",
      "Kwanjiku",
      "Lembus",
      "Limunga",
      "Mairo",
      "Majani",
      "Melwa",
      "Mugeno",
      "Mugumo",
      "Muguongo",
      "Mukunga",
      "Munanda",
      "Mungetho A",
      "Mungetho B",
      "Munyu",
      "Ndemu",
      "Ngarachi",
      "Njoguini",
      "Ol Ngarua",
      "Oljabet",
      "Outspan",
      "Sironi",
      "St Paul Ndagara",
      "Thigio",
      "Thiru",
      "Karandi Primary",
      "Lokiriama",
      "Kirima",
      "Lelematesho",
      "Chongoti",
      "Gatuikira",
      "Huhoini",
      "Kiahiti",
      "Kiahuko",
      "Kiamariga A",
      "Kiamariga B",
      "Kianjogu",
      "Kiriko",
      "Kirima",
      "Marura",
      "Mathira",
      "Matigari",
      "Mayu",
      "Muruai",
      "Muruku",
      "Mutara B",
      "Muthigia",
      "Ndaragwiti",
      "Nganoini",
      "Nguu",
      "North Tetu",
      "Raya",
      "Rhoda",
      "Salama",
      "Nkiroriti",
      "Kisiriri",
      "Maendeleo",
      "Kinamba",
      "Mutara A",
      "Kambi Simba",
      "Naserian",
      "Nkloris",
      "Eloiloi",
      "Rugongo",
      "Laikipia Campus",
      "Huhoini",
      "Shemanei",
      "Karangi",
      "Igwamiti",
      "Losogwa",
      "Kigumo",
      "Ngare Naro",
      "Mariakan",
      "Bethel",
      "Kiheo",
      "Thama",
      "Rwathia",
      "St Luis",
      "Nyahururu Deb",
      "Mt Angels",
      "91 Municipality",
      "Kaichakun A",
      "Kaichakun B",
      "Gatero",
      "Muthengera",
      "Mukurweini",
      "Lokiriama",
      "Maina",
      "Huruma Maina",
      "Kundarilla",
      "Munungaini",
      "Uaso Narok",
      "Mukutwini",
      "Manguo",
      "Starehe",
      "Miharati",
      "Kio",
      "Wangwachi",
      "Bondeni",
      "Kaharati",
      "Sipili School Of Deaf",
      "Laikipia Ranching",
      "Nagum",
      "Naiborom",
      "Sipili",
      "Marura",
      "Mbogoini",
      "Chemi Chemi",
      "Dimcom",
      "Mahinga",
      "Nyanjara",
      "Kabati",
      "Lariak",
      "Ririchua",
      "Kiriani",
      "51 Nursery",
      "Bahati Ecde",
      "Kahari Ecde",
      "Kaptagat Ecde",
      "Machunguru Ecde ",
      "Mutamayu Ecde",
      "Mwireri Ecde ",
      "Ndurumo Ecd ",
      "Omc Ecde",
      "St Lwanga Ecde",
      "Rumuruti Ecde",
      "Olari Nyiro B",
      "Kambi Simba",
      "Ainamoi A",
      "Kapkures",
      "Ainamoi B",
      "Olari Nyiro A",
      "Simitwo",
      "Momboini",
      "Muricho",
      "Magomano",
      "Mathuri",
      "Nanyuki Muslim",
      "Nanyuki Garrison",
      "Police Line",
      "Kanyoni",
      "1 Kr Ecd",
      "Mt Kenya Primary",
      "Nturukuma",
      "Nkando",
      "Nanyuki Children Home",
      "Likii",
      "Nanyuki Ecd",
      "Muthaiga",
      "Muthaiga",
      "St Moses",
      "Nanyaki Deb",
      "Laikipia Airbase Ecd",
      "Temmakis",
      "Mirera",
      "Mwiruti",
      "Bungoma",
      "Ndururi",
      "Thingithu",
      "Njogu Ini",
      "Sweetwater",
      "Matanya",
      "Yard Deb",
      "Irura",
      "Oltaffeta",
      "Ruai",
      "Nyambugichi",
      "Suguroi",
      "Ngobit",
      "Bridge",
      "Vision",
      "Munyaka",
      "Mutaro",
      "Mwituria",
      "Shallom Centre",
      "Sinai",
      "Githira",
      "Bahati",
      "Ihigaini",
      "Wamura",
      "Tetu Wamburi",
      "Kijabe",
      "Segera",
      "Gachoro",
      "Withare",
      "Nguthiru",
      "Shallom Cannan",
      "Imenti",
      "Rutunguru",
      "Sirima",
      "Naituruchi",
      "Mwireri",
      "Karungu",
      "Kariguini",
      "Karimaini",
      "Muhonia",
      "Mahiga Meru",
      "Marina",
      "Mwihoko",
      "Metha",
      "Mathenya",
      "Gieterero",
      "Mutara",
      "Marichu",
      "Ngano",
      "Nyariginu",
      "Daiga",
      "Tetu",
      "Mugumo",
      "Matuiku",
      "Gitugi",
      "Umande",
      "Nyakiambi",
      "Kirimara",
      "Gakeu",
      "Makutano",
      "Ruai",
      "Kaumbuku",
      "Ndemu",
      "Murungai",
      "Kalalu",
      "Tumaini",
      "Perez",
      "Bingwa",
      "Mt Kenya",
      "Bingwa",
      "Bahati DEB ecd",
      "Baraka solio ecde",
      "Chuma ecd",
      "Chuma B ecd",
      "Furaha ECD ",
      "Imara ECDE center",
      "Iriuko ecd",
      "Kabanga ecd",
      "Karai ecd ",
      "Kiambiriria ecd",
      "Kibubungi ecd ",
      "Kiburi ecde",
      "Kihato ecd",
      "Lechugu ecd",
      "Male ecde",
      "Mathingira solio ecde",
      "Mitero ecd",
      "Mother Teresa",
      "Mukandamia solio ecde",
      "Mukuri ecde",
      "Mwiyogo ecde",
      "Nyakio day care nursery",
      "Makogeni",
      "Ihigiani ecd centre",
      "Kiburuti",
      "Riacho ecde",
      "Solio DEB Ecd ",
      "Tetu DEB Solio ranch solio ecde",
      "Tharua ecde",
      "Tigithi ecd",
      "Waguthiru ECDE",
      "Wathituga ecde",
      "Weruini ecd",
      "Asis",
      "Itet",
      "Imaniat",
      "Kaburgei",
      "Kalyet",
      "Lelabei",
      "Manyatta",
      "Moiben Upper",
      "Mosop",
      "Mumetet",
      "Ngoisa",
      "Ranymoi",
      "Sesia",
      "Tachassis",
      "Toloita",
      "Kabatu",
      "Tangururen",
      "Itet B",
      "St Marys Tachassis",
      "Kimogoch ECD",
      "Kapsiliot",
      "Kapkoros",
      "Chemweno Chebor",
      "Mindililwo",
      "Cheplaskei",
      "Konginyalil",
      "Meibeki",
      "Kapnasu",
      "Tangasir",
      "Endao",
      "Bidii",
      "Seretyo",
      "Kemeliet",
      "Muget",
      "Sasitwo",
      "Chebaon",
      "Chesongor",
      "Kapsundei",
      "Cheptigit",
      "Brockley",
      "Naiberi",
      "Kipsinende",
      "Koibarak",
      "Ngatit",
      "Plateau",
      "Berur",
      "Chepnoet",
      "Kiluka",
      "Kongasis",
      "Kipkoriony",
      "Uhuru",
      "Kapsemwo",
      "Tendwo",
      "Aic Kaptagat Children S Home",
      "Lotonyok",
      "Chepkoilel Central",
      "Chepkoilel Central",
      "Koilel",
      "Koilel",
      "Chepkero",
      "Chepkoilel Central",
      "Kiburer",
      "Munyaka",
      "Ilula",
      "Saroiyot",
      "Kapsoya",
      "Border Farm",
      "Arangai Primary Ecd ",
      "Arap Moi",
      "Arnesens Ecde",
      "Chelelek Primary School",
      "Chepngoror Ecde",
      "Drys Farm Ecd",
      "Kapkeno Ecde",
      "Kewet Primary Ecde",
      "Kimuruk Primary Ecd",
      "Kipteimet Ecd Centre",
      "Ndanai Primary",
      "Ngarua Primary",
      "Olare Ecde",
      "Rurigi Primary Ecde",
      "Saito Ecd Centre",
      "Siliboi Ecd Centre",
      "Skyline Primary School",
      "Soliat Primary",
      "Tingwa Ecde",
      "Kitoroch",
      "Central Ecd",
      "Eldoret Chebarus",
      "Eldoret G.K Prison ",
      "Greenfield",
      "Ngomongo Ecd",
      "Moi University  Chepkoilel ",
      "Ainabtich",
      "Moi Marula",
      "Kimumu",
      "Ack Kapkorio",
      "Arbabuch Ecde",
      "Chebarus.C. Ecde",
      "Chepngochoch",
      "Chepkoilel North",
      "Emsilies Primary School",
      "Charar Ecde",
      "Kabuliot Ecde",
      "Aic Kaprobu Primary School",
      "Kapsubere",
      "Karona Ecd",
      "Kiriswo Primary School",
      "Maua Ecd",
      "Kapchesimbol",
      "Sosiyo Ecd",
      "Tilatil Ecd",
      "Torochmoi Ecde",
      "Tugen Estate",
      "Kaptich",
      "Baharini Primary",
      "Chelugui",
      "Chepkongony Ecde",
      "Chepkurmum Ecd ",
      "Chororget Primary School",
      "Kabore",
      "Katuiyo Primary School",
      "Kipkabus Upper Ecd",
      "Koilonget Ecde",
      "Lelek ",
      "Leltot Ecde",
      "Rot Tuga Primary School",
      "Sirwo Ecd Center",
      "Songich Ecd Centre",
      "Usalama Ecd Centre",
      "Waunifor",
      "Chelalang Ecd",
      "Cheburbur Ecd Centre",
      "Chelelmetio Ecd Centre",
      "Chemaluk",
      "Chemarmar Ecd",
      "Chemungen Ecde",
      "Chepkosom Primary",
      "Kamokono Ecd Centre",
      "Kaperi Primary",
      "Aic Kapkei Primary Ecd",
      "Kaplogoi",
      "Kapsoen Ecde ",
      "Kaptuktuk Aic Edce",
      "Kimoning",
      "Kimore Primary",
      "Kimuchi Ecd",
      "Kipleketet Primary Ecd",
      "Rcea Koitoror Ecde",
      "Kombaemit",
      "Kuryot",
      "Lelit",
      "Mutei Ecde ",
      "Ruiyobei Primary Ecd ",
      "Seiyo",
      "Sergoit Rcea Primary ",
      "Simotwet",
      "Soin Ecd",
      "Sorngetuny Primary Ecd",
      "Sosiot",
      "Tuiyoluk Ecde",
      "Chebarus",
      "Atnas Kandie",
      "Emkoin",
      "Huruma",
      "Kapkeben",
      "Kapkoros",
      "Kapyemit",
      "Kapsaos",
      "Uasin Gishu",
      "Aic Cheplelaibei",
      "Aic Kabobo",
      "Aic Lalakin",
      "Aic Saniak",
      "Aic Sinendet",
      "Aic St Barnabas",
      "Chemoset",
      "Chemororoch",
      "Kamoiywa",
      "Kapkatet",
      "Kapsang",
      "Kapsumbeiywet",
      "Kaptait",
      "Kaptebengwet",
      "Kesogon",
      "Kipsangui",
      "Kipsomba",
      "Kipsomba Farm",
      "Kosyin",
      "Kisabei",
      "Lorwa",
      "Mobett",
      "Mogoiywet",
      "Ripmoy",
      "Sinonin",
      "Soy",
      "St Vincenttuisuswo",
      "Teldet",
      "Vumilia",
      "Kiwato",
      "St Marys Ngobitwa",
      "Kimorwet",
      "Kuresok",
      "Saramek",
      "Sda Segero",
      "Chepkigen",
      "St Mathews Lamaiywet",
      "Nukiat",
      "Ainamoi Sda",
      "Makongi",
      "Sisyobei Sda",
      "Kongasis",
      "Kapngetuny",
      "Segero",
      "Legebet",
      "Sachangwan",
      "Roret Sda",
      "Kimurgoi",
      "Chelabal",
      "Kerotet",
      "St Thomas Mararai",
      "Aic Tamboiyot",
      "Ziwa",
      "Emdin",
      "Sirikwa",
      "Kimnyigei",
      "Kimolwet",
      "Kwenet",
      "Bwayi",
      "Kipketiegwet",
      "Moisbridge",
      "Cheptarit",
      "Sigaon",
      "Maendeleo",
      "Lamaiywet",
      "Matunda Rc",
      "Kapkoren",
      "Ndabarnach",
      "Kapkures",
      "Jabali",
      "Mukunga",
      "Natwana",
      "Aic Tenai",
      "Kilima",
      "Bondeni",
      "Aic Mogoon",
      "Maji Mazuri",
      "Cci Nabiswa",
      "Aic Itigo",
      "Chepkongi Primary Ecd",
      "Greenfield",
      "Kidiwa",
      "Kapchumba Ecde",
      "Aic Kapkuis",
      "Kiptanui",
      "Koitebes Ecd",
      "Kuinet Primary Ecd",
      "Leiboinet ",
      "Limnyomoi Primary Ecd",
      "Shirika Primary Primary",
      "St Paters Kamukunji",
      "Emkwen Ecde",
      "Kaaboi Ecde",
      "Kapleketet Ecd Center",
      "Kaplelach North$",
      "Kiplombe Ecde Center",
      "Kolongei Ecd",
      "Township Primary Ecd Unit",
      "Union Nursery",
      "St.Marys",
      "St.Patricks",
      "Sigowet Ecde Centre",
      "Tebeswet Ecd Centre",
      "Chebarus",
      "Ainamoi",
      "Kapchumba",
      "Barsombe Primary Ecde",
      "Chepterit Primary Ecde",
      "Cheukta Ecde",
      "Kambugu Ecde Centre",
      "Kiborokwa Ecde Centre",
      "Kokwet Ecde Centre",
      "Lamaon Ecd Centre",
      "Lemoru Primary School",
      "Kapkoros Gaa Primary School",
      "Lolkinyei Ecde Centre",
      "Lower Moiben Ecde Centre",
      "Mafuta Primary School",
      "Milimani Primary School",
      "Ngeny Ecd Centre",
      "Nyalilbei Ecde Centre",
      "Cheptuon Ecde",
      "Sugutek Ecdd Centre",
      "Boinet Ecde",
      "Chebarus Primary",
      "Chemalal Ecde Centre",
      "Chepkoiyo North Ecde",
      "Chepkumia Ecde",
      "Ack Cheramei Ecd",
      "Kapkong Ecd",
      "Kaptich Ecde Centre",
      "Kipkeino School Ecd",
      "Kosachei Ecde",
      "Kuresieti Ecde Centre",
      "Leseru Ecde Centre",
      "Lower Sosiani Ecde",
      "Manzini Ecde",
      "Mokoiywo Ecd",
      "Cheptabach North Ecde",
      "Aic Seiyot Ecde Centre",
      "Sokyot Ecd",
      "St Pauls Kenduywo",
      "Sugoi Ecde",
      "Tuiyobei Ecde",
      "Ainopngetich",
      "Sambut",
      "Kamagut",
      "Moi Barracks",
      "Samoei Model",
      "Chemalal "B"",
      "Ack St Stephen",
      "Sugoi Gaa",
      "Sosiani Pmca",
      "Mareba",
      "Chepkongi",
      "Symbiosis",
      "Chepkoilel",
      "Emgwen Emsos",
      "Besiebor",
      "Chepkatet",
      "A.I.C Kipyonget Ecd Centre",
      "Aic Tap Sagoi Ecd Centre",
      "Aic Tarus Ecd Primary School",
      "A.I.C Tiret Ecde",
      "Aic Besiebor Ecd Centre",
      "Bukwo Primary Ecde",
      "Chebaiywa Primary School Ecd",
      "Chepkatet Hills",
      "Chepkemel Ecd",
      "Chepsaita Ecde",
      "Elgon Estate Ecde",
      "Kapkures Hill ",
      "Kaptendon",
      "Kipyonget Hill Ecd Centre",
      "Kombaeren Primary School",
      "Labuiywetprimary",
      "Lower Kipkaren Ecd Centre",
      "Moro Primary School",
      "Murgor Hills Ecde",
      "Murgusi Primary School",
      "Mwangaza  Ecde",
      "Ng'Enyilel Primary Ecd",
      "Mlimani Ecde",
      "Upendo Ecde",
      "Holy Rosary Primary School Ecde",
      "Tuiyobei-Gaa Primary School",
      "Soin",
      "St. Columban'S Ecd Centre",
      "Emkoin",
      "St Peters Kapkechui",
      "Tendwa Osorongai",
      "Tuigoi Primary Ecde",
      "Chepkoiyo",
      "Kimoiywet",
      "Kapkatet",
      "Asururiet",
      "Barekeiwo",
      "Bindura",
      "Cheboror",
      "Chuiyat",
      "Kamuyu",
      "Kapchorua",
      "Kapserton",
      "Koisagat",
      "Kapilat",
      "Koisolia Primary",
      "Lainguse",
      "Ndungulu",
      "Ngeny",
      "Sengalo",
      "Sigilai",
      "St Marks Teldet",
      "Tulwet",
      "Tumoge",
      "AIC Messis",
      "Deb Momoniat",
      "Chesunet",
      "Moi University",
      "Aic Kosirai",
      "Aic Belekenya",
      "Konyit",
      "Murgor",
      "Lelmolok",
      "Ketiplong",
      "Ochemina",
      "Aic Chebaiywo Ruman",
      "Kibabet",
      "Legetet",
      "Kabongwa",
      "Barnotik",
      "Lelmokwo",
      "Songoliet",
      "Chepkoiyo",
      "Tulwopngetuny",
      "Lingwal",
      "Davies",
      "Ngeria",
      "Chepkoiyo South",
      "Chepkoiyaa",
      "Koiwarusen",
      "Sambul",
      "Kapkoi",
      "Chepkitiny",
      "Kapranga",
      "St Cornelius Tilolwa",
      "Kaplamai",
      "Timboroa",
      "Silagaa",
      "Toror",
      "Koriomat",
      "Kipkorosyo",
      "Kipkorosyo",
      "Subukia",
      "Koiluget",
      "Chagaiya",
      "Muchorwe",
      "Chemare",
      "Matharu",
      "Lingway",
      "Kiptega",
      "Nabkoi Boys",
      "Tarakwa",
      "Emgwen Koitebes B",
      "Chirchir",
      "St Catherine Kahuho",
      "Koitebes",
      "Boror",
      "Rukuini",
      "Kapyemit Primary School",
      "Kapkenduiywo",
      "Kipkenyo",
      "Tuiyoibei",
      "Gitwe",
      "St Marys Chebarus",
      "Sosiani",
      "Langas",
      "Kimalel",
      "Oasis",
      "Mwiruti",
      "Kipkaren",
      "Pioneer",
      "Racecourse",
      "Saroiyot",
      "Sugunanga",
      "Apuoyo",
      "Barkawandu",
      "Dienya",
      "Ginga V",
      "Karuwa",
      "Kayieye",
      "Komuok",
      "Malunga",
      "Nyagondo",
      "Nyasidhi",
      "Ober",
      "Opal",
      "Orombe",
      "Uriri",
      "Wagai",
      "Wagwer",
      "Wangoji",
      "Ulamba",
      "Kaumeri",
      "Kotoo",
      "Kanyilangi",
      "Bar Katado",
      "Nyapiego",
      "Pala Valley",
      "Uganga Ecde",
      "Jina Ecde",
      "Jm Rembe Ecde",
      "Ahono Ecde",
      "Marengo Ecde",
      "Ulumbi Ecde",
      "Yala Township Ecde",
      "Bar Juru Ecde",
      "Tatro Ecde",
      "Anyiko",
      "Nyamninia Ecde",
      "Muhanda Ecde",
      "Bar Sauri Ecde",
      "St Teresa Ecde",
      " Kojuok Ecde Centre",
      "Rawalo Ecde Centre",
      "Masinde Ecde Centre",
      "Olengo Ecde Centre",
      "Nyawara Ecde Centre",
      "Gongo Ecde",
      "Kagilo Ecde Centre",
      "Karariw Ecde Centre",
      "Luri Ecde Centre",
      " Migosi Ecde Centre",
      "Nango Gonda Pry Sch",
      "Siriwo Ecde Centre",
      "Ulamba Ecde Centre",
      "Nyawara Ecde Centre",
      "Ahono",
      "Barkalare",
      "Kanyuto",
      "Lihanda",
      "Marenyo",
      "Midhine",
      "Mingawo ",
      "Nyangulu",
      "Omindo Ecde Centre",
      "Onding Ecd",
      "Rabuor",
      "Ramula",
      "Sagam",
      "Sinaga",
      "Uranga",
      "St Georges Sidada Primary",
      "Asayi Ecde Centre",
      "Bar Komeno",
      "Gogo",
      "Got Kokwiri",
      "Ligoma",
      "Lundha",
      "Malanga ",
      "Maliera",
      "Masene",
      "Miro",
      "Mulare Ecd ",
      " Mundoware Ecde",
      "Musembe Ecde Centre",
      "Mutumbu Ecd",
      "Mwadi Ecde Centre",
      "Ndere Mixed Ecd",
      "Nyabeda",
      "Regrea Ecde",
      "Sanjro",
      "Sirandu",
      "Sirembe",
      "Sirodha Ecd",
      "Ujimbe",
      "Unami",
      "Simpsons Academy",
      "St. Annes Academy",
      "Ndori",
      "Aluor",
      "Oasis Of Hope Academy",
      "Abuche Primary School Ecde Center",
      "St Bonface Aluor Mixed",
      "Dhene",
      "Kambare",
      "Kanyadet",
      "Kaudha Ecd",
      "Kudho",
      "Malele Ecd Center",
      "Nyalunya Primary Ecd Centre",
      "Nyamkiria Ecd",
      "Odendo",
      "Odok Rera",
      "Ojola",
      "Ojwach",
      "Ojwaya",
      "Onyinyore",
      "Oseno Primary Ecd Center",
      "Powo Rasanga",
      "Rachare",
      "St Oda For The Blind",
      "Usenge",
      "Uthanya",
      "Wambusa",
      "Wangbith",
      "Wangu",
      "Siala Ecd",
      "Akuom",
      "Barkogonga",
      "Gagra",
      "Got Okola",
      "Gotkojwang",
      "Kagwa",
      "Kahoya",
      "Kawuondi",
      "Komolo",
      "Langu",
      "Madiany",
      "Majengo",
      "Manywanda",
      "Misori",
      "Nyabera",
      "Nyakongo",
      "Ogango",
      "Ojawa",
      "Othoche",
      "Pala Kobong",
      "Rachar",
      "Tanga",
      "Tuju",
      "Wagoro",
      "Wambisa",
      "Mirando",
      "Magare",
      "Malanga",
      "Kolo",
      "Kasiri",
      "Kunya",
      "Ragengni",
      "Migowa",
      "Maramba",
      "Kayundi",
      "Ochienga",
      "Kobonyo",
      "Chianda",
      "Lusi",
      "Kasiri",
      "Kayundi",
      "Nyamasore",
      "Ruma",
      "Dagamoyo",
      "Okela",
      "Ndhere ECDE Center",
      "Masala ECDE Center",
      "Powo Ecde",
      "Boi Ecde",
      "Wera Ecde",
      "Gunda Rut Ecde",
      "Lela Ecde",
      "Ramba Ecde",
      "St Lazarus",
      "Kusa Ecde",
      "Oboch Ecde",
      "Kamalumbe Ecde",
      "Kamin Ogedo Ecde",
      "Ongielo Ecde",
      "Kandhere Ecde",
      "Kanyichudo Ecde",
      "Kokise Ecde",
      "Aduoyo Ecde",
      "Raliew Ecde",
      "Nguka Ecde",
      "Kitambo Ecde",
      "Got Bondo",
      "Konjiko Ecde",
      "Alara Ecde",
      "Kandaria Ecde",
      "St Nicholas Kaonje Ecde",
      "Rariw Ecde",
      "Luoro Ecde",
      "Okiro Ecde",
      "Naya Ecde",
      "Otieno Sibuor Luanda Kotieno",
      "Mirau",
      "Ranyala Ecde",
      "Kadundo Ecde",
      "Nyangoye Ecde",
      "Ndigwa Ecde",
      "Ndonyo Ecde",
      "Mituri Ecde",
      "Mumbo Ecde",
      "Malanga Ecde",
      "Wayaga Ecde",
      "Lweya Ecde",
      "Agok Ecde",
      "Lwala Rahongo Ecde",
      "Rabel Ecde",
      "Ramoya Ecde",
      "Lieta Ecde",
      "Buru Ecde",
      "Madiany Special School",
      "Akom Ecde",
      "Gangu Ecde ",
      "Kametho",
      "Kawamang'Aria",
      "Kawino Primary Ecde Center ",
      "Kiswaro Primary School Ecd Center ",
      "Lwak Mixed Ecd",
      "St Claire Ecde Centre",
      "Mabinju",
      "Mahaya ",
      "Majango Ecde Centre",
      "Manera",
      "Maugo Ecd Centre",
      "Memba Ecd",
      "Ndwara Ecde",
      "Nyagoko Primary School Ecde Center",
      "Nyamboyo Ecde",
      "Nyamor Primary School Ecde Center ",
      "Obaga",
      "Omboye Primary School Ecde Center ",
      "Rakombe",
      "Rambira",
      "Rambugu",
      "Rarieda Ecd",
      "Sangla",
      "Siger",
      "Atemo",
      "Ujwanga Ecde",
      "Wang'Arot",
      "Olago",
      "Alara",
      "Dago",
      "Lenya",
      "Luore",
      "Migiro",
      "Ndeda",
      "Nyangoma",
      "Nyangoma Girls",
      "Nyangoma Mixed",
      "Onyinyore",
      "Oyamo",
      "Rabango",
      "Uyawi",
      "Wambarra",
      "Warianda",
      "Odao",
      "Ulanda",
      "Miyandhe",
      "Sifu",
      "Sarawongo",
      "Mawere Ecde",
      "Bar Opuk Ecde",
      "Ngulu Ecde",
      "Manyonge Ecde",
      "Okola Ecde",
      "Abom Ecde",
      "Sirembe Ecde",
      "Bar Kowino Ecde",
      "Siage Ecde",
      "Bar Kuogo Ecde",
      "Atilili Ecde",
      "Kibuye Ecde",
      "Diera Aora Ecde",
      "Dunya Ecde",
      "Barmuofu Ecde",
      "Matangwe Ecde",
      "Waringa Ecde",
      "Ndira Ecde",
      "Nyabenge Ecde",
      "Keyo Kodindo Ecde",
      "Majiwa Ecde",
      "Kamnara Ecde",
      "Lwala Ecde",
      "Ajigo Ecde",
      "Kayogo Ecde",
      "Gobei Ecde",
      "Bar Chando Ecde",
      "Mbeka",
      "Burlowo",
      "Arude",
      "Migono",
      "Utuoma Ecde",
      "Uhendo",
      "Barkawaga Ecde",
      "Bondo Mix",
      "Goma",
      "Gunda Sigomre",
      "Kambajo Ecd",
      "Kapiyo Ecde",
      "Magawa",
      "Maranda Ecd",
      "Masita",
      "Mikenga Ecd",
      "Ndhere Ecde",
      "Nyakasumbi Ecde",
      "Nyamira Mixed",
      "Nyandusi Ecde",
      "Nyawita",
      "Obedi",
      "Sinapanga",
      "Sinyanya",
      "Ugathi Ecd",
      "Uloma Ecde",
      "Yieke Ecde",
      "Nyamwanga",
      "Agwara",
      "Abidha",
      "Bur Yiro",
      "Chunga Ecde Centre",
      "Got Matar Ecde Centre",
      "Kasau Ecde Centre",
      "Maco Ecde",
      "Magombe Ecd",
      "Muguna Ecde",
      "Ndiwo Ecde Centre",
      "Nyamonye Ecde Centre",
      "Odhuro Ecd",
      "Oele Ecde",
      "Othach",
      "Pala Ecde Centre",
      "Paplela Ecde",
      "Ragar Ecde",
      "Uhanga Ecde Centre",
      "Humwendi",
      "Harungu Primary",
      "Lung'a",
      "Milambo",
      "Magombe",
      "Ndenga",
      "Nyaharwa",
      "Sifuyo",
      "Siginga",
      "Uriya",
      "Kanyaundo Primary",
      "Uyundo Primary",
      "Bar Anyanga",
      "Nyalenya",
      "Ogeya",
      "Waliera",
      "Miyare",
      "Ng'ang'a",
      "Hafumbre",
      "Got Odima",
      "St Joseph Ochiel",
      "Bar Oninge",
      "Got Rembo",
      "Pap Olang",
      "Majengo",
      "Bar Awendo",
      "Mahanga",
      "Jusa",
      "Rapogi",
      "Sangwe",
      "Nyangera",
      "Got Ramogi",
      "Usenge",
      "Mitundu",
      "Mageta",
      "Ndere Alinga",
      "Wambasa",
      "Nyabondo",
      "Kanyibok",
      "Nyayo",
      "Sika",
      "Ulowa",
      "Sanda",
      "Mahwi",
      "Uringi",
      "Nyamsenda",
      "Anyiko Primary School",
      "Bar Ndege",
      "Buranga Primary",
      "Inungo Primary",
      "Kodongo",
      "Komoro",
      "Konya",
      "Luanda",
      "Luthehe",
      "Murumba",
      "Nyalenda",
      "Nyangungu",
      "Ramunde",
      "Sirisia Primary",
      "Uchola Primary School",
      "Ukela",
      "Umer",
      "Urenga",
      "Usinda",
      "Mathiwa",
      "Uhola Ecd Centre",
      "Bar Odar Primary Ecde Centre",
      "Got Nanga Primary School Ecde Center ",
      "Jera Ecd Centre",
      "Kagonya Primary Ecde Centre",
      "Kogere Primary Ecde Centre",
      "Lela Ecd",
      "Ligala Ecd ",
      "Ligose Primary School Ecde Center ",
      "Mauna Ecd",
      "Nyambiro Primary School Ecde Center ",
      "Ralak",
      "Sega Girls Ecde Centre",
      "Sega Township Primary",
      "Udira Kamrembo Ecde",
      "Ugambe Ecde Centre",
      "Abimbo Ecde",
      "Chamagaha Ecd",
      "Gombe Primary School Ecde Center",
      "Got Abiero",
      "Got Achieng Ecd",
      "Kipasi",
      "Magak Primary School Ecde Center",
      "Maranyona Ecde",
      "Mitiro Primary School Ecde Center ",
      "Nyaguda Ecde ",
      "Orengo Ecde",
      "Ouya Ecde Center ",
      "Thim Primary School Ecde Center ",
      "Akoko Ecde",
      "Kamrembo Siwandhe",
      "Siwar Ecde Centre",
      "Lwero",
      "Got Omalo Ecde Centre",
      "Nzoia Ecde Centre",
      "Simur Ecde Centre",
      "Doho",
      "Diraho",
      "Lifunga",
      "Sigweng Karuoth",
      "Siranga Ecde Centre",
      "Udhine",
      "Ukwala Boys Ecde Centre",
      "Ukwala Girls",
      "Yenga",
      "Rarieda Uyore Ecde",
      "Agulu Ecde",
      "Pal Pal Ecde",
      "Nyagwela Ecde",
      "Osoro Ecde",
      "Nyadhi Ecde",
      "Sirongo Ecde",
      "Gendro",
      "Segere Ecde",
      "Ngura Ecde",
      "Aduwa Ecde",
      "Pap Boro Ecde",
      "Kibar E Cde",
      "Urim Ecde",
      "Obambo Ecde",
      "Nyalula Ecde",
      "Kanyaboli Ecde",
      "Ndai Ecde",
      "Boro Ecde",
      "Kalenjuok Ecde",
      "Uyiko Ecde",
      "Kochieng Ecde",
      "Liganwa",
      "Bar Kaguanda Ecde",
      "Usula Ecde",
      "Magungu Ecde",
      "Agage Ecde",
      "His Blessings Ecde",
      "Agoro Tula Ecde",
      "Agoro Oyombe Ecde",
      "Nyang Oma Kogello Ecde",
      "Mur Malanga Ecde",
      "Nyang Inja Ecde",
      "Ndisi Ecde",
      "Uloma Kodero Ecde",
      "Rapogi Ecde",
      "Matera Ecde",
      "Kirindo Ecde",
      "Ng Iya Mixed Ecde",
      "Sigana Ecde",
      "Rambo Ecde",
      "Ochilo Ecde",
      "Nyajuok Ecde",
      "Ojwando Ecde",
      "Rakuom Ecde",
      "Ochiewa Ecde",
      "Upanda Ecde",
      "Usingo Ecde",
      "Barding Ecde",
      "Agoro Lieye Ecde",
      "Bar Agulu Ecde",
      "Pap Oriang Ecde",
      "Asere Ecde",
      "Nduru Ecde",
      "Thim Ralak Ecde",
      "Nyanganga Ecde",
      "Pap Gori Ecde",
      "Bar Olengo Ecde",
      "Mugane Ecde",
      "Pap Nyadiel Ecde",
      "Uuna Ecde",
      "Katuda Ecde",
      "Masumbi Ecde",
      "Ngiya Girls Boarding",
      "Sarah Obama ECDE",
      "Bible Baptist Church And School",
      "Bright Light Community Centre",
      "Children Angels Of God Project",
      "Elim Primary School",
      "Kabiro Primary",
      "Kawangware Mck Academy",
      "Keds Care Community School",
      "Love School Centre",
      "Mabe Twinkling Stars School",
      "Madaraka Community Centre",
      "Nairobi Language Institute",
      "Rens Community Centre",
      "Riri Junior Academy",
      "The Excellence School",
      "Beso Phil Community Centre",
      "Free Methodist Academy Kawangware",
      "Gladways Centre",
      "Godrich School",
      "Kids Empowerment Centre",
      "Light Christian Education Center",
      "Mwangaza United Community Center.",
      "Sifa Childrens Centre",
      "Skylife Childrens Centre",
      "Upako Centre",
      "Vineyard Community Centre",
      "Wamo Non_ Formal Education Centre",
      "Besure Earlychildhood Care Centre",
      "Blood Of Jesus School(Ever School)",
      "Childrens Of Africa Hope Mission School",
      "Frank Education ",
      "Glads Kids Foundation Center",
      "Jolliday Children Community Center",
      "Junction Joy Community Centre",
      "Lenana  Junior Community School",
      "Lizpal Foundation Centre",
      " The Amaf Schools.",
      "Peak Educational Center",
      "Precious Talents Top School",
      "Riruta Israel Academy",
      "St Joseph Of Tarbes Primary School",
      "St Austine Educational Center",
      "Stemi Junior Community Center",
      "Chn St Catherine Children Education Center",
      "Chema Vision Children Center",
      "Fairview Children Center",
      "Galilaya Door Of Hope Education Center",
      "Hoywick Academy School",
      "Joysprings Educational Center",
      "Kag Olympic Educaton Center",
      "Shammah Childrens Centre",
      "Tunza Children Center",
      "Jeremic Advestist Academy",
      "Kids School",
      "Spurgeons Academy",
      "St Michaels Holy Unity Academy",
      "St Christine Education Center",
      "Three Bells Primary School",
      "St Paul Kindergarten And Centre",
      "Greenlight Educational Centre",
      "Oases Community Centre",
      "Good Hope",
      "Mars Star School",
      "Kabiria Cornerstone Centre",
      "Tender Feet",
      "Bensesa",
      "Bignet Education Centre",
      "Glorious Climbers Educational Centre",
      "Back To Glory Achievers School",
      "Catessam Education Centre",
      "Dosabi Blessed Centre",
      "Brightburn School",
      "Alpha Glory School",
      "Adventure Pride Centre",
      "Akili Complex",
      "Anwa Junior Academy",
      "Calvary Primary",
      "Egesa Children Centre",
      "Holly Trinity Education Centre",
      "Kicoshep Laini Saba Primary",
      "Makina Baptist Primary School",
      "Makina Self Help Primary School",
      "Mercy Junior Educational Center",
      "Optimist Educational Centre",
      "Patmos School",
      "Restoration Education Centre",
      "Ujamaa Community Based School",
      "Alfa Kids Educational Centre",
      "Blessed Vision Learning Centre",
      "Brilliant Junior Learning Centre",
      "Chariot Educational Centre",
      "Dajan By Faith Learning Centre",
      "Efama Education Centre",
      "Green Plains Academic Project",
      "Jonasta School",
      "Lawna Educational Learning Centre",
      "St Jecinta Junior Christian School",
      "St Joseph Resource Centre",
      "St Jude Academic Project",
      "Sta Shake Education Centre",
      "Super Star Educational Centre",
      "Winners Education Centre",
      "Codeman Academy",
      "Daystar Junior Education Centre",
      "Genesis Joy Project Institute",
      "Kanyaa Primary School",
      "Mathare Community Outreach Joy",
      "Mathare Community Outreach 4 B",
      "Mcedo Beijing Education Centre",
      "Pilot Education Daycare Centre",
      "St James Feeding Prog Learning Project",
      "Star Education Centre",
      "Caso Upendo Academy",
      "Karuna Giris Educational Centre",
      "Mathare Brilliant Academy",
      "Mathare North Adventist Education Centre",
      "Mawewa School",
      "Mercy Care Centre",
      "Sterlurm Elite School",
      "Bringers Of Joy Education Centre",
      "Davis Junior School",
      "Maxdais Education Centre",
      "Amito Junior School",
      "Amson Education Centre",
      "Betterlife Community Centre",
      "Ebenizer Kim Day Care",
      "Jojo Junior Educational Centre",
      "Menno Kids Education Centre",
      "Miracle Junior Community Centre",
      "Queenrose Daycare",
      "Sega Holistic Education Centre",
      "Shaperner Children Centre",
      "St Christopher Wholistic School",
      "Stellamarris Community School",
      "Succses Junior School",
      "Wisdom Seaker Centre",
      "Young Heirs Education Centre",
      "Christian Family Education Centre",
      "Covenant Shield Junior Centre",
      "Friends Educational Centre",
      "Great Hope Network Children Centre",
      "Highridge Hope Education Centre",
      "Happy Angels Education Centre",
      "Korogocho Children Development Centre",
      "Korogocho B Nfe School",
      "Faith For All N Ministries",
      "Silver Plate",
      "St Johns Primary School",
      "Korogocho Glory Nursery And Primary School",
      "Ufanisi Centre",
      "Rijah Junior Academy",
      "Rehema Day Care And Orphans Centre",
      "St Mary S",
      "Grogon A School",
      "St Lucy Educational Centre",
      "Alpha And Omega",
      "Aic Kariobangi Self Help Group School",
      "Asulma Center",
      "Bright Angels Education Centre",
      "Deligent Ecde Centre",
      "Exodus School",
      "Imani School Ecde",
      "Joyfull Springs Learning Centre",
      "Kariobangi Community Outreach",
      "Mt. Kenya Preparatory",
      "Real Queens And Kings",
      "Kariobangi Baptist Education Center",
      "Savyo Bells Education Center",
      "Sparkle Academy",
      "St Joel School Ecde",
      "Neema Development Centre",
      "Mt Morriah Community Centre",
      "Gracious Juniour School",
      "Eden Annex Preparatory School",
      "Divine Education Centr",
      "Mastered Educational Centre",
      "Main Preparatory Centre",
      "Glorious Rehabilitation Centre",
      "Sandota Education Centre",
      "Danna Hills Education Centre",
      "Takrima Education Centre",
      "Geonan Day School",
      "Good Hope Academy",
      "Njiris Education Centre",
      "Dammy Junior School",
      "St Linet Elite Learning Centre",
      "Ambassador Community Centre",
      "Angaza Preparatory School",
      "Christian Growth Education Centre",
      "Galilee Primary School",
      "Genesis Juniour Centre",
      "Graceline Educational Center",
      "Highlight Junior Academy",
      "Kwa Watoto School",
      "Merryland Community Centre",
      "New Joy Children Center",
      "Presbyterian Education Center",
      "Sheepcare Comminity Centre",
      "Soweto Baptist Shinning School",
      "St Micah Community Centre",
      "St Arnold Janssen Primary School",
      "St Placida Preparatory School",
      "Vessel Of Hope Education Centre",
      "Maendeleo Learning Centre",
      "Mwangaza Tumaini Centre",
      "Kids Of Hope Education Centre",
      "St James Academy",
      "Vision Day Care Education Centre",
      "Hopevine Junior Academy",
      "Downstream Community Centre",
      "Jocada Community School",
      "Glorious Land Academy",
      "Church Of The Rock Learning Centre",
      "Jophen Primary",
      "Huruma Community School",
      "Green Mount",
      "Isaiah Kings",
      "St Junior",
      "Fair Oak",
      "Joyland Academy",
      "Wisdom Junior Education Centre",
      "Blessed Heart Centre",
      "Tender Heart Education Centre",
      "Unity Academy Centre",
      "Sibiah Star School",
      "Vision Achievers Preparatory School",
      "Blessed Hope Community Centre",
      "Bookyard Education Centre",
      "Future Leaders Learning Centre",
      "Elmond Ecd Centre",
      "Brilliant Learning Centre",
      "Joyland Education Centre",
      "Kingdom Life Educational Centre",
      "Kingdom Champions Academy",
      "Middle South Junior Academy",
      "Good Beginning Educational Centre",
      "Glory Elite School",
      "Gateway Junior Education Centre",
      "Bright Learning Centre",
      "Gift Of Hope Learning Centre",
      "Fekija Vision Centre",
      "Cool Morning Education Centre",
      "St Peters Day Care Centre",
      "Chrisco Kayole Education And Empowerment Centre",
      "St Winners Education Centre",
      "Sharp Education Centre",
      "Hope Of The City",
      "Willy Junior Community Centre",
      "Hilltop Learners Centre",
      "Lovely Ones Education Centre",
      "Genesis Schools",
      "Umoja Land",
      "Bethjoy Academy",
      " Bright Star Academy",
      "Brooklane School",
      "Glory Learning Centre",
      "Hosmark Academy",
      "Junior Willy Academy",
      "Little Angles Education Centre",
      "Olive Shoot",
      "Oliveshoot Center",
      "Richmas Juniour School",
      "Tasia Sda Educational Center",
      "Town Send Academy",
      "Victory Learning Centre",
      "Waterfords Golden Hearts School",
      "Gracious School",
      "Bidii Self Help Nursery And Primary School",
      "Kangemi Youth Centre",
      "Spc Education Centre",
      "Oasis Primary",
      "Marga Education Centre",
      "Milkan Elite School",
      "Alfa Education Centre",
      "Sweet Angels Shg",
      "Umoja Academy",
      "Teravic Education Centre",
      "Stev In Education Centre",
      "Vinestar Academy",
      "St Martins",
      "Young Angels Education Centre",
      "Sprigoh Education Centre",
      "Shyrock Academy And Kindergaten",
      "Jupiter Academy",
      "Jolly Land Academy",
      "Hope Of Light Education Centre",
      "Evalon Education Centre",
      "Dandora Minorate Education Centre",
      "Bright Future Community School",
      "Ruai Township Academy",
      "Abimasi Junior School",
      "St Agnes Junior School Centre",
      "Lunjeki Junior School",
      "Jimindi Shg Academy",
      "St Peters Preparatory School",
      "Young Stars School",
      "Blessed Hope Community Centre",
      "Precious Junior School",
      "Friends Junior Community School",
      "Future Kids Junior Educational Centre",
      "Blessed Star Academy",
      "Luna Junior Academy",
      "Rofra Junior Academy",
      "Torati Educational Centre",
      "Maryland Academy And Community Centre",
      "Agano Junior Academy",
      "Gate Pass Junior School",
      "Innocent Souls Education Centre",
      "Good Day Centre",
      "Josana Day School And Centre",
      "Ark Community Education Center",
      "Clean Win Education Center",
      "Furaha Preparatory School",
      "Genesis Kindergarten Annex Primary School",
      "Hope Compassion Center",
      "Josama Community Ecde Centre",
      "Kag Mathare",
      "Little  Bees  School",
      "Mabawa School Kosovo",
      "Hch Madoya Centre",
      "Mothers Joy Academy",
      "St. Martin Deporres",
      "Twinstar Junior Academy",
      "Upendo Children  Education  And  Centre",
      "Viara Junior Academy",
      "Kisumu Ndogo Nyayo Kdn",
      "Day Shelter Centre Korogocho",
      "Damascus Education Center",
      "Altaawon Educational Centre",
      "Makao Junior School",
      "Jambo Toto School",
      "The Shelter Centernkorogocho",
      "Big Ben Academy",
      "Grace Given Education Centre",
      "Hekima Day Care And Primary",
      "New Hope Centre",
      "Revealed Educational Centre",
      "Maranatha Korogocho Church School",
      "Tumaini Learning Centre",
      "Tradiona Birth Attendants",
      "Agoro Tula Ecd Centre",
      "Barkodhiambo Primary School",
      "Gombe Komolo Ecd",
      "Got Oyenga Ecd",
      "Hono Ecde",
      "Kowet Primary",
      "Manyala Ecde",
      "Mbaga Mixed Ecde",
      "Nina Ecde Centre",
      "Nina School For The Deaf",
      "Nyakongo Kokang",
      "Nyamila",
      "Oseno Komolo Ecd",
      "Rachuonyo",
      "Ulafu Ecde Center",
      "Ulafu Ecde Centre",
      "Umala",
      "Usula Ecde Centre",
      "Uyoma Ecd",
      "Yogo Ecde",
      "Nyalukunga Ecde",
      "Rabango Ecd Centre",
      "Achage Ecd Primary ",
      "Anduro Ecd Centre",
      "Awelo Ecd Centre",
      "Siaya Central Ecd",
      "Gombe Komolo Ecd Centre",
      "Karapul Ecd Centre",
      "Naaman Akuma Ecd Centre",
      "Nyandiwa Ecd Centre",
      "Siaya Township Ecd Centre",
      "Uhongo Ecd Centre",
      "Bukhoba Ecde Centre",
      "Dibuoro Ecd",
      "Goro Ecde Centre",
      "Kamalunga Ecd",
      "Lolwe Ecd Centre",
      "Mahero Ecd",
      "Nyambare Ecd",
      "Sidundo Ecd",
      "Udamayi Ecd Centre",
      "Uhembo Ecd",
      "Ulupi Ecde Centre",
      "Uwasi Ecde Centre",
      "Nyadheho Ecd",
      "Duha Centre",
      "Hawinga Ecd",
      "Kabura",
      "Kabura Ulwan",
      "Kalkada Primary Ecde Centre",
      "Karadier Ecd Centre",
      "Mahola Ecde Centre",
      "Malomba Primary Ecde Centre",
      "Misori Ecd  Primary ",
      "Mwer Ecd",
      "Ndiwo Centre",
      "Nyakado Ecde Centre",
      "Nyalaji Ecd Centre",
      "Nyalwanga",
      "Nyasita Ecde Centre",
      "Gospel For Peace Ecde Centre",
      "Pap Olengo",
      "Rasugu Ecd Centre",
      "Sidok Ecd",
      "Sirinde Ecd ",
      "Sudhe Ecd Centre",
      "Udenda Ecd",
      "Uhuyi Ecd",
      "Ulawe Apate Ecd Centre",
      "Unyolo Ecd Centre",
      "Uradi",
      "Wang Chieng",
      "Luanda",
      "Lunjre Ecde Centre",
      "Markuny",
      "Mayingo",
      "Mudhiero",
      "Murumba Yiro",
      "Nyiera Ecde Centre",
      "Rangala Primary Ecde",
      "Ruwe",
      "Sidindi",
      "Sijimbo",
      "Sikalame",
      "Sikang Ecde Centre",
      "Simenya",
      "Ugolwe Ecde Centre",
      "Wang Otong",
      "Bar Atheng",
      "St Dominic Uloma Ecde Center",
      "Lunjre Ecde Centre",
      "Ninga",
      "Sigomre",
      "Got Osimbo",
      "Hawagaya",
      "Madungu",
      "Luoka ",
      "Luru",
      "Ugana",
      "Uluthe",
      "Msiko",
      "Lukongo",
      "Ligala Kabiero",
      "Ulanda",
      "Ngop Misengni",
      "Ywaya",
      "Ginga",
      "Ichinga",
      "Tihinga",
      "Krind",
      "Orawo",
      "Asango",
      "Ukalama",
      "Masamra Primary School Ecde Center ",
      "Dendyo Primary School Ecde Center ",
      "Rambula Ecde Centre",
      "Ambira Primary School Ecde Center ",
      "Bar Atheng",
      "Daho Ecde Center",
      "Konjra",
      "Mauna",
      "Mbosie",
      "Mudaho Ecde Centre",
      "Nyamasare",
      "Nyasanda Primary School Ecde Center ",
      "Ogeda",
      "Raduodi Ecde Center",
      "Sango Ecde Centre",
      "Siror Ecde Centre",
      "Suwinga",
      "Ugunja Primary School Ecde Center ",
      "Ulawe Ecde Centre",
      "Ulwani",
      "Ulumba Ecde Center",
      "Uref",
      "Uria Magoya",
      "Chebii Ecd Centre",
      "Chemenei Ecde Centre",
      "Cheplosgei Ecde",
      "Cheptiret Ecd Centre",
      "Chesegem Ecde Centre",
      "Chuchuniat Ecd Centre",
      "Kaptumo Ecde",
      "Keringet",
      "Kerita Ecde",
      "Kerita Kosyin Ecde",
      "Kerita Tulwet Ecde",
      "Kileges",
      "Lengut",
      "Mogobich Ecde Centre",
      "Mogocheret",
      "Mugondoi Ecde Centre",
      "Rehema Ecde",
      "Seiyo Primar Ecd Centre",
      "St. Matthews Kipchamo Ecde",
      "Ack Aturei Ecde",
      "St Augustines Borderland",
      "Chepyakwai Primary",
      "Hill School Ecde",
      "Inder Ecde Centre",
      "Jasho Primary",
      "Kamuzee  Primary Ecd",
      "Kapkagaron",
      "Kapsaret",
      "Kaptinga Ecde Centre",
      "Kermetio Ngeny",
      "Kiamba Ecd",
      "Kimuri Ecd",
      "Kipkaren Airport Primary",
      "Kipsamoo Primary",
      "Koibasui Primary ",
      "Lemook Ecde",
      "Mutwot",
      "Nandi Gaa Ecd",
      "Ngara Falls Primary Ecd",
      "St Anne Ecde Centre",
      "Pmca Chepkongi Ecde Centre",
      "Sda Aturei Ecde",
      "Simat Ecde Centre",
      "St.Georges",
      "St.James Leberio",
      "St John Kabongo",
      "St.Joseph",
      "St  Marys Chelabal Ecd ",
      "Tuiyo",
      "Ngunya",
    ]
  end

  def self.closest_valid_school_match(school_name)
    return school_name.upcase if self.valid_schools.include? school_name.upcase
    return FuzzyMatch.new(self.valid_schools).find(school_name.upcase)
  end

  # Poorly named
  def self.closest_school_match(school_name)
    self.closest_valid_school_match(school_name)
  end

  def self.error_from_invalid_kenya_school(school_name)
    return nil if self.valid_schools.include? school_name.upcase
    closest_match = FuzzyMatch.new(valid_schools).find(school_name.upcase)
    return "#{school_name} is not a valid school. Do you mean #{closest_match}?"
  end
end
